/*
 Quantcast measurement tag
 Copyright (c) 2008-2021, Quantcast Corp.
*/
(function(b,f,e){try{__qc("defaults",b,{labels:"_fp.event.Default"})}catch(k){}var g=function(b){var a=e.createElement("a");a.href=b;return a},h=function(b,a,c){return b?"nc"===b?!a||!c||0>a.indexOf(c):"eq"===b?a===c:"sw"===b?0===a.indexOf(c):"ew"===b?(b=a.length-c.length,a=a.lastIndexOf(c,b),-1!==a&&a===b):"c"===b?0<=a.indexOf(c):!1:!1},a=function(a,b,c){var d;d=f.top===f.self?e.location.href:g(e.referrer).href;h(b,d,c)?a(d):a(!1)},c=function(a){return"array"==={}.toString.call(a).match(/\s([a-zA-Z]+)/)[1].toLowerCase()?
{labels:a.join(",")}:{labels:""+a}};__qc.apply(null,["rules",[b,null,[[c,"_fp.event.FLEX Demo Request TY"]],[[a,"c","ahoy.twilio.com/flex-request-demo-ty"]]],[b,null,[[c,"_fp.event.Email API"]],[[a,"c","twilio.com/sendgrid/email-api"]]],[b,null,[[c,"_fp.event.SMS Messaging"]],[[a,"c","twilio.com/messaging"]]],[b,null,[[c,"_fp.event.Power of Programmability TY"]],[[a,"c","/flex-power-of-programmability-demo-ty"]]],[b,null,[[c,"_fp.event.Power of Programmability"]],[[a,"c","/flex-power-of-programmability-demo"],
[a,"nc","/flex-power-of-programmability-demo-ty"]]],[b,null,[[c,"_fp.event.SIP Trunking"]],[[a,"c","sip-trunking"]]],[b,null,[[c,"_fp.event.Interactive Demo Form Fill"]],[[a,"c","twilio.com/flex/interactive-demo"]]],[b,null,[[c,"_fp.event.Insights"]],[[a,"c","/flex-insights-demo"]]],[b,null,[[c,"_fp.event.Omnichannel"]],[[a,"c","/flex-omnichannel-demo-request"]]],[b,null,[[c,"_fp.event.Interactive Demo"]],[[a,"c","/flex-in-action-demo"]]],[b,null,[[c,"_fp.event.Pricing"]],[[a,"c","https://www.twilio.com/pricing"]]],
[b,null,[[c,"_fp.event.Partner Solutions"]],[[a,"c","https://www.twilio.com/partner-solutions"]]],[b,null,[[c,"_fp.event.Partner Solutions"]],[[a,"c","https://www.twilio.com/partner-solutions"]]],[b,null,[[c,"_fp.event.Customers"]],[[a,"c","https://www.twilio.com/customers"]]],[b,null,[[c,"_fp.event.Solutions"]],[[a,"c","https://www.twilio.com/solutions"]]],[b,null,[[c,"_fp.event.Events"]],[[a,"c","https://www.twilio.com/events"]]],[b,null,[[c,"_fp.event.Flex Omnichannel Demo Request"]],[[a,"eq",
"https://ahoy.twilio.com/flex-omnichannel-demo-request"]]],[b,null,[[c,"_fp.event.flex request demo 2"]],[[a,"eq","https://ahoy.twilio.com/flex-request-demo-2"]]],[b,null,[[c,"_fp.event.flex request Demo 3"]],[[a,"eq","https://ahoy.twilio.com/flex-request-demo-3"]]],[b,null,[[c,"_fp.event.Learn More Flex"]],[[a,"eq","https://www.twilio.com/flex"]]],[b,null,[[c,"_fp.event.Twilio Whatsapp"]],[[a,"c","https://www.twilio.com/whatsapp"]]],[b,null,[[c,"_fp.event.Wireless"]],[[a,"c","https://www.twilio.com/wireless"]]],
[b,null,[[c,"_fp.event.Use Cases"]],[[a,"c","https://www.twilio.com/use-cases"]]],[b,null,[[c,"_fp.event.SMS"]],[[a,"c","https://www.twilio.com/sms"]]],[b,null,[[c,"_fp.event.Company"]],[[a,"c","https://www.twilio.com/company"]]],[b,null,[[c,"_fp.event.Console"]],[[a,"c","https://www.twilio.com/console"]]],[b,null,[[c,"_fp.event.Chat"]],[[a,"c","https://www.twilio.com/chat"]]],[b,null,[[c,"_fp.event.Blog"]],[[a,"c","https://www.twilio.com/blog/"]]],[b,null,[[c,"_fp.event.Voice"]],[[a,"c","https://www.twilio.com/voice"]]],
[b,null,[[c,"_fp.event.Products"]],[[a,"eq","https://www.twilio.com/products"]]],[b,null,[[c,"_fp.event.Flex Demo Request Received"]],[[a,"eq","https://ahoy.twilio.com/request-flex-demo-ty"]]],[b,null,[[c,"_fp.event.Flex Request Demo"]],[[a,"eq","https://www.twilio.com/flex/request-demo"]]],[b,null,[[c,"_fp.event.Flex Stay Updated"]],[[a,"eq","https://www.twilio.com/flex/stay-updated"]]],[b,null,[[c,"_fp.event.Sales"]],[[a,"c","https://www.twilio.com/help/sales"]]],[b,null,[[c,"_fp.event.Sign Up"]],
[[a,"c","https://www.twilio.com/try-twilio"]]],[b,null,[[c,"_fp.event.Login"]],[[a,"c","https://www.twilio.com/login"]]],[b,null,[[c,"_fp.event.Docs"]],[[a,"c","https://www.twilio.com/docs"]]],[b,null,[[c,"_fp.event.Try"]],[[a,"c","https://www.twilio.com/try-twilio"]]],[b,null,[[c,"_fp.event.Homepage"]],[[function(a,b,c){var d;d=f.top===f.self?e.location.pathname:g(e.referrer).pathname;h(b,d,c)?a(d):a(!1)},"eq","/"]]]])})("p-efmoRQHrDUXig",window,document);